### ISSUE TITLE
API Endpoint of PowerApps for Admins

### ISSUE THREAD

**Issue by Disha5195** [megel/powerapps-helper#14]
Hello Megel,

Thank you for the powerapps-helper documentation and endpoints.
I need some more help to get API endpoint of powerapps for admins connector.
I couldn't get the documentation from microsoft as well.
https://docs.microsoft.com/en-us/connectors/powerappsforadmins/  
Any help would be really appreciated!

Thank you!

**Comment by megel** [comment]
@Disha5195 which API are you looking for?

I got the API information direct from Microsoft Sources - like the PowerShell module 

When you unpack the .nuget package for `Microsoft.PowerApps.Administration.PowerShell`, unzip and look and search for your API (e.g. `Get-AppQuarantineState`) then you find in `Microsoft.PowerApps.Administration.PowerShell.psm1` this:
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/15800069/147449390-5b519656-fc50-4fed-9215-53d943ab3605.png">

From here, you see "mostly" the route and used parameters of the API.
 
Hope this helps!

**Comment by megel** [comment]
@Disha5195 if you have further questions, please contact me. I'll close the issue.
