### ISSUE TITLE
Power Apps: Download and Unpack Solution Error

### ISSUE THREAD

**Issue by LegionDevOps** [megel/powerapps-helper#5]
Hi,
sorry to bother you, but I have the following problem.

When I want to download and unpack a Solution, I get the following error message:
 Command 'Power Apps: Download and Unpack Solution' resulted in an error (command 'mme2k-powerapps-helper.solution.downloadAndUnpack' not found).

Do you know how I can solve this problem?

Thank you and kind regards

**Comment by megel** [comment]
Hi, how did you start action 'Power Apps: Download and Unpack Solution'?

**Comment by LegionDevOps** [comment]
Hi,
my OS: macOS Catalina Ver. 10.15.7
VScode Ver. 1.57.1

I start the action with 'command+shift+p' and choose 'Power ....'

**Comment by megel** [comment]
I guess the OS is the Problem. I have changed the tooling libraries to the latest Microsoft Power Platform CLI, which is probably not compatible with MacOS. 
Can you please try to install the Power Platform CLI from [https://docs.microsoft.com/en-us/powerapps/developer/data-platform/powerapps-cli](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/powerapps-cli)
Afterwards configure the PAC.exe or similar (😁 I have no Mac and don't know what is installed) in the vscode settings.

**Comment by LegionDevOps** [comment]
😄ok, thx, I try it

**Comment by megel** [comment]
Did you try? If yes, did it work 😅 However, there might be another issue on MacOS with storing secret information for OAuth Update. This is because I use [keytar](https://www.npmjs.com/package/keytar) as dependency:
https://github.com/megel/powerapps-helper/blob/ae418823c764839d2d207cd620d8098b0f8be222/package.json#L354

... and this is - I guess - not supported on MacOS ... maybe you have an idea to handle this

**Comment by megel** [comment]
@LegionDevOps I have wrapped the usage of `keytar` to avoid errors during usage. Furthermore contains the current release **0.7.1** some improvements for MacOS.

You should now be able to:
* Pack / Unpack PowerApps using Power Platform Cli
* Pack / Unpack Dataverse solutions using Power Platform Cli

**Comment by pwshdevops** [comment]
I have an issue with unpacking as well. I was able to get the command to run manually, grabbing the command from the output window.

`RUN: "c:\Users\User\AppData\Roaming\Code\User\globalStorage\microsoft-isvexptools.powerplatform-vscode\pac\tools\pac.exe" canvas unpack --msapp "c:\Options\PowerApps/[redacted].msapp" --sources "c:\Options\PowerApps/src/[redacted]/"
Error: Command failed: "c:\Users\User\AppData\Roaming\Code\User\globalStorage\microsoft-isvexptools.powerplatform-vscode\pac\tools\pac.exe" canvas unpack --msapp "c:\Options\PowerApps/[redeacted].msapp" --sources "c:\Options\PowerApps/src/[redeacted]/"`

I changed the direction of the slashes to follow the Windows format and added the required "." prior to the executables filepath.

The follow-on issue, is that my .msapp name had spaces in it. The unpacking process wouldn't complete until I renamed the file to something with no spaces.

**Comment by megel** [comment]
@pwshdevops spaces shouldn't be the problem, because the path is masked by `"`. Which OS do you use?

**Comment by megel** [comment]
@pwshdevops I assume, you have found a solution. I'll close this issue.
