### ISSUE TITLE
[Discussion] Consider using the Power Platform CLI that is installed by Power Platform VS Code Extension

### ISSUE THREAD

**Issue by Chris-WP** [megel/powerapps-helper#8]
The blog post [Power Platform Command Line and Power Platform Tools for Visual Studio Code June Update](https://powerapps.microsoft.com/en-us/blog/power-platform-command-line-and-vs-code-extension-june-update/) (dated 21 July 2021) suggests using the PowerPlatform CLI version installed by the [Power Platform VS Code Extension](https://marketplace.visualstudio.com/items?itemName=microsoft-IsvExpTools.powerplatform-vscode) rather than the Standalone Power Platform CLI.

Specifically it states:
```We would encourage folks to use the Power Platform Tools for VS Code over the standalone Power Platform CLI, as it lines better with some of the developer inner-loop functions```

This could be accommodated by changing the default of the Power Platform CLI location to the path that is installed by the VS Code extension to:

```%APPDATA%\Code\User\globalStorage\microsoft-isvexptools.powerplatform-vscode\pac\tools\pac.exe``` rather than ```%LOCALAPPDATA%\Local\Microsoft\PowerAppsCLI\pac.cmd```

and by providing a link (displayed as part of the VS Code settings/preferences item) to the VS Code extension rather than the StandalonePower Platform CLI installer:

<https://marketplace.visualstudio.com/items?itemName=microsoft-IsvExpTools.powerplatform-vscode>

**Comment by megel** [comment]
@Chris-WP yes, this is a better solution. I need to investigate, what I have to change 😅

**Comment by megel** [comment]
@Chris-WP good news, I have now integrated to Power Platform Cli as dependent extension and use the PAC tool from there. Additionally, you can also configure an own PAC installation when needed.

Implemented in [PR #8](https://github.com/megel/powerapps-helper/issues/8)
